// Offline, non-prescriptive field guidance. Local partners can replace these
// entries with approved country/crop protocols without changing the model.
window.CROP_KNOWLEDGE = {
  "Cerscospora": {action:"Mark the affected coffee plant and inspect nearby leaves in the same row.", monitor:"Check whether round leaf spots increase after wet weather and whether more plants are affected.", avoid:"Do not make a pesticide decision from this screen; ask the local extension contact to verify the cause."},
  "Healthy": {action:"Use this photo only as a local comparison; keep scouting nearby leaves.", monitor:"Check the underside and new growth after rain or unusual leaf drop.", avoid:"Do not conclude that the farm is disease-free from one image."},
  "Leaf_rust": {action:"Treat this as a priority signal: mark the plant and inspect leaf undersides and neighbouring plants today.", monitor:"Record whether yellow-orange powdery lesions or new affected leaves are appearing.", avoid:"Do not move wet leaves, tools, seedlings or harvested material between plots before local advice."},
  "Miner": {action:"Mark affected plants and inspect several leaves for fresh tunnels or damaged tissue.", monitor:"Check whether damage is increasing on new leaves and across nearby rows.", avoid:"Do not choose a treatment based on a photo result alone; confirm locally first."},
  "Phoma": {action:"Mark the plant and collect a clear follow-up photo of the leaf and surrounding plants.", monitor:"Check whether dark spots are expanding and whether symptoms increase after wet weather.", avoid:"Do not treat or remove plants based only on this model result; request local verification."},
  "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": {action:"Mark affected patches and inspect lower leaves first.", monitor:"Check whether lesions are expanding after rain or prolonged leaf wetness.", avoid:"Do not share saved seed or move wet plant material between fields."},
  "Corn_(maize)___Common_rust_": {action:"Inspect both leaf surfaces and flag the first affected rows.", monitor:"Look for new orange-brown pustules on young leaves every 3–4 days.", avoid:"Do not use this screen alone to choose a fungicide."},
  "Corn_(maize)___Northern_Leaf_Blight": {action:"Map plants with long cigar-shaped lesions and remove badly damaged leaf debris after harvest.", monitor:"Track spread along prevailing wind and after humid periods.", avoid:"Do not compost visibly diseased residues unless the local protocol permits it."},
  "Corn_(maize)___healthy": {action:"Keep this plot as a comparison photo for nearby symptomatic plants.", monitor:"Recheck after rain, irrigation changes, or when new symptoms appear.", avoid:"Do not treat a healthy-looking leaf preventively from this result alone."},
  "Pepper,_bell___Bacterial_spot": {action:"Avoid handling plants while foliage is wet; separate tools used in affected rows.", monitor:"Look for water-soaked spots and leaf drop, especially after splashing rain.", avoid:"Do not save seed from symptomatic plants or move transplants from the area."},
  "Pepper,_bell___healthy": {action:"Keep this photo as a local healthy reference.", monitor:"Inspect new growth and underside of leaves weekly.", avoid:"Do not infer that the whole field is disease-free from one leaf."},
  "Potato___Early_blight": {action:"Flag plants with older-leaf lesions and remove severely affected leaves only if local guidance supports it.", monitor:"Check older foliage first and note whether concentric lesions are increasing.", avoid:"Do not leave infected crop waste beside the field or use this as a treatment prescription."},
  "Potato___Late_blight": {action:"Treat this as urgent: separate suspect plants and notify the local extension contact today.", monitor:"Check neighbouring plants for fast-spreading dark, water-soaked lesions.", avoid:"Do not move tubers, cuttings, or wet foliage from the suspect plot."},
  "Potato___healthy": {action:"Use this leaf as a healthy comparison and continue routine scouting.", monitor:"Inspect after cool, wet weather and compare with nearby plants.", avoid:"Do not treat based solely on a healthy classification."},
  "Tomato___Early_blight": {action:"Mark affected plants and inspect lower, older leaves for expanding target-like lesions.", monitor:"Track whether symptoms increase after leaf wetness or rain.", avoid:"Do not work from affected to healthy rows without cleaning hands and tools."},
  "Tomato___Late_blight": {action:"Treat this as urgent: isolate suspect plants and contact the local extension service today.", monitor:"Inspect adjacent plants for rapidly expanding dark lesions, especially after humid weather.", avoid:"Do not move transplants, cuttings, fruit crates, or wet foliage from the plot."},
  "Tomato___healthy": {action:"Keep this photo as a healthy reference for this plot.", monitor:"Scout new and lower leaves twice a week during wet periods.", avoid:"Do not conclude that the entire crop is disease-free from one image."}
};
